import type { Metadata } from "next";
import { FC, PropsWithChildren, Suspense } from "react";
import "./globals.css";
import MainHeader from "../layouts/MainHeader";
import Providers from "../layouts/Providers/Provider";
import { Modal } from "../components/Modal";
import { AdapterProvider } from "@/context";
import InitializeService from "./InitializeService";
import { getCoinsService } from "@/services/handler";
import { BalanceProvider } from "@/context/Balance";

export const metadata: Metadata = {
  title: "Baryon",
  description: "Generated by create turbo",
};

export default async function RootLayout({
  children,
}: Readonly<PropsWithChildren>) {
  const { coinLocal, coinGecko } = await getCoinsService();

  return (
    <html lang="en" data-theme="dark" className="dark">
      <body>
        <AdapterProvider>
          <BalanceProvider>
            <Providers>
              <MainHeader />
              <Suspense>
                <InitializeService coinGecko={coinGecko} coinLocal={coinLocal} />
                {children}
              </Suspense>
              <Modal />
            </Providers>
          </BalanceProvider>
        </AdapterProvider>
      </body>
    </html>
  );
}
