import type { Metadata } from "next";
import { FC, Suspense } from "react";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

// Define a type for the Layout props
type LayoutProps = {
  children: React.ReactNode;
};


const Layout: FC<LayoutProps> = ({ children }) => {
  return (
    <html lang="en">
      <body>
        <Suspense>
          {children}
        </Suspense>
      </body>
    </html>
  );
}

export default Layout;
